PR1-OE12-Test-Management/config/routes.rb
Rails.application.routes.draw do
  get "sessions/new"
  scope "(:locale)", locale: /en|vi/ do
    get "users/new"
    get "/signup", to: "users#new"
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users
  end
end

PR1-OE12-Test-Management/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

PR1-OE12-Test-Management/app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save {email.downcase!}
  validates :name, presence: true, length: {maximum: Settings.User.number}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: Settings.User.number1},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: {minimum: Settings.User.number2}
  class << self
    def digest string
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
      BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end

    def authenticated? remember_token
      return false if remember_digest.nil?
      BCrypt::Password.new(remember_digest).is_password?remember_token
    end
  end

  def remember
    self.remember_token = User.new_token
    update remember_digest: User.digest(remember_token)
  end

  def forget
    update remember_digest: nil
  end
end

PR1-OE12-Test-Management/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    {locale: I18n.locale}
  end
end

PR1-OE12-Test-Management/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new;  end

  def create
    user = User.find_by email: params[:session][:email].downcase
    if user&.authenticate params[:session][:password]
      log_in user
      params[:session][:remember_me] == "1" ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = t ".invalid"
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

PR1-OE12-Test-Management/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def about; end

  def contact; end
end

PR1-OE12-Test-Management/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by id: params[:id]
    return if @user
    flash[:danger] = t ".nouser"
    redirect_to root_path
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      flash[:success] = t ".welcome"
      redirect_to @user
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation
  end
end

PR1-OE12-Test-Management/app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t ".title2"
    page_title.empty? ? base_title : page_title + " | " + base_title
  end
end

PR1-OE12-Test-Management/app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by id: user_id
    elsif user_id = cookies.signed[:user_id]
      user = User.find_by id: user_id
      if user&.authenticated? cookies[:remember_token]
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    current_user.present?
  end

  def forget user
    user.forget
    cookies.delete :user_id
    cookies.delete :remember_token
  end

  def log_out
    forget current_user
    session.delete :user_id
    @current_user = nil
  end
end

PR1-OE12-Test-Management/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

PR1-OE12-Test-Management/app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user
    gravatar_id = Digest::MD5::hexdigest user.email.downcase
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

PR1-OE12-Test-Management/app/views/layouts/_footer.html.erb
<footer class="footer-navbar">
  <div class="languages">
    <%= t ".Languages" %>
    <%= link_to t(".En"), locale:"en" %>
    <%= link_to t(".Vi"), locale:"vi" %>
    <% provide :title, t(".title1") %>
  </div>
  <div class="footer-author">
    <%= t(".app") %> <%= link_to t(".quiz"), Settings._footer.linkf1 %>
    <%= t(".by") %> <%= link_to t(".author"), Settings._footer.linkf2 %>
  </div>
</footer>

PR1-OE12-Test-Management/app/views/layouts/_header.html.erb
<header class ="header-navbar">
  <div class ="header-container">
    <%= link_to t(".quiz"),root_path , id:"logo" %>
    <nav>
      <ul class ="nav navbar-right header-menu">
        <li><%= link_to t(".home"), root_path %></li>
        <li><%= link_to t(".help"), help_path %></li>
        <li><%= link_to t(".about"), about_path %></li>
        <li><%= link_to t(".contact"), Settings._footer.linkf3 %></li>
        <% if logged_in? %>
          <li><%= link_to t(".user"), '#' %></li>
          <li class="header-dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t ".account" %> <b class="caret"></b>
            </a>
            <ul class="header-dropdown-menu">
              <li><%= link_to t(".profile"), current_user %></li>
              <li><%= link_to t(".setting"), '#' %></li>
              <li>
                <%= link_to t(".log"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

PR1-OE12-Test-Management/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

PR1-OE12-Test-Management/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t ".title2" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

PR1-OE12-Test-Management/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t ".form" %> <%= pluralize @user.errors.count, t(".err") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

PR1-OE12-Test-Management/app/views/static_pages/about.html.erb
<div class="index_main">
  <div class="about_main">
    <h1> <%= t ".titles" %> </h1>
  </div>
</div>

PR1-OE12-Test-Management/app/views/static_pages/contact.html.erb
<div class="index_main">
  <div class="contact_main">
    <h1> <%= t ".contact" %> </h1>
    <h3>
      <%= t ".contact1" %>
      <%= link_to t(".contact2"), Settings.contact.linkc %>
  </h3>
  </div>
</div>

PR1-OE12-Test-Management/app/views/static_pages/help.html.erb
<div class="index_main">
  <div class="help_main">
    <h1> <%= t ".title3" %> </h1>
  </div>
 </div>

PR1-OE12-Test-Management/app/views/static_pages/home.html.erb
<div class="index_main">
  <h1> <%= t ".title1" %> </h1>
</div>

PR1-OE12-Test-Management/app/views/users/new.html.erb
<% provide :title, t(".sign") %>
<h1> <%= t ".sign" %> </h1>
<div class="row">
  <div class="signup_form">
    <%= form_for @user, url: signup_path do |f| %>
      <%= render "shared/error_messages" %>
      <%= f.label :name, t(".name") %>
      <%= f.text_field :name, class: "form-control" %>
      <br>
      <%= f.label :email, t(".email") %>
      <%= f.email_field :email, class: "form-control" %>
      <br>
      <%= f.label :password, t(".pass") %>
      <%= f.password_field :password, class: "form-control" %>
      <br>
      <%= f.label :password_confirmation, t(".password_confirmation") %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
      <br>
      <%= f.submit t(".create"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

PR1-OE12-Test-Management/app/views/users/show.html.erb
<% provide :title, @user.name %>
<div class="row">
  <aside class="user_show">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>